{%- if vm['provider'] == 'docker' %}
FROM {{ vm['os'] }}


SHELL ["/bin/sh", "-c"]


ADD src/file.cpp /usr/include/mylib/file.cpp




COPY src/file.cpp /usr/include/mylib/file.cpp


RUN ["/bin/bash", "-c", "echo hello"]
RUN /usr/sbin/nologin
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install nginx
RUN ["c:\\windows\\system32\\tasklist.exe"]


WORKDIR /path/to/workdir

{%- endif %}





