# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  config.vm.define "VM1" do |node|
    node.vm.box = "generic/ubuntu1910"
    node.vm.network "private_network", ip: "172.16.1.101"
    node.vm.network "forwarded_port", guest:80, host:8080, host_ip:"127.0.0.1"
  end
end