# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  
  config.vm.define "VM1" do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostonly_network "private_network", ip: "172.16.1.101"
    # node.vm.network "forwarded_port", guest: 22, host: 2202, host_ip:"127.0.0.1"
    # node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip:"127.0.0.1"
  end
  
  config.vm.define "VM2" do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.hostonly_network "private_network", ip: "172.16.1.102"
    # node.vm.network "forwarded_port", guest: 22, host: 2203, host_ip:"127.0.0.1"
  end
  
end