# Dockerfile for service: nginx
FROM amd64/ubuntu:16.04
WORKDIR /nginx
RUN set -x \
    && apt-get update \
    && apt-get install -y \
    curl \
    gettext-base \
    build-essential \
    libpcre3 \
    libpcre3-dev \
    libpcrecpp0v5 \
    libssl-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && curl -SL http://nginx.org/download/nginx-1.3.9.tar.gz | tar -xzv \
    && cd nginx-1.3.9 \
    && ./configure \
    --prefix=/usr \
    --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log \
    --http-log-path=/var/log/nginx/access.log \
    --pid-path=/var/run/nginx.pid \
    --lock-path=/var/lock/nginx.lock \
    --with-http_ssl_module \
    --user=www-data \
    --group=www-data \
    --with-http_stub_status_module \
    --with-http_gzip_static_module \
    --without-mail_pop3_module \
    --without-mail_imap_module \
    --without-mail_smtp_module \
    && make \
    && make install
CMD ["nginx","-g","daemon off;"]