# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.synced_folder "/share/ven/esys", "/share/ven/esys", mount_options: ['rw', 'exec'], create: true, disabled: true
  # vagrant plugin install vagrant-disksize
  # config.disksize.size = '40GB'
  config.vm.define "log4shell" do |node|
    node.vm.hostname = "log4shell"
    node.vm.box = "ubuntu/focal64"
    node.vm.network "private_network", ip: "192.168.56.100", name: "lan1"
    node.vm.network "forwarded_port", guest: 22, host: 2202, auto_correct: true
    node.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    node.vm.provider :virtualbox do |provider|
      provider.customize ["modifyvm", :id, "--cpus", "1"]
      provider.customize ["modifyvm", :id, "--memory", "4096"]
      provider.customize ["modifyvm", :id, "--vrde", "on"]
	  provider.customize ["modifyvm", :id, "--vrdeport", "12345"]
      provider.customize ["modifyvm", :id, "--vrdeaddress", "0.0.0.0"]
    end
    # node.vm.provision "shell", path "log4shell.conf.sh"
  end
end