# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box_check_update = false
  config.vm.synced_folder "/share/ven/esys", "/share/ven/esys", create: true
  config.vm.synced_folder "/proj/TechDemo/malware/esys", "/proj/TechDemo/malware/esys", create: true,
    mount_options: ['rw', 'exec']
  config.vm.define "attacker_and_victim" do |node|
    node.vm.box = "gusztavvargadr/windows-10-enterprise"
    node.vm.network "private_network", ip: "192.168.56.100"
  end
end
